### ISSUE TITLE
Infinite loop?

### ISSUE THREAD

**Issue by giordi91** [hmatuschek/eigen3-nnls#1]
Hi, I gave a try to the header and gave somewhat good result.
One of the problem is that sometimes it just goes into an infinite loop and hangs it there. 
I am not an expert at all in LS or NNLS implementation so my question is, if that kind of behaviour is common? If not can be solved ?  I think my data set was roughly correct, covering enough samples to have a good span. So even if with relative big error a result should have been found?

Best Regards and thanks for your effort.

**Comment by hmatuschek** [comment]
Although this behavior is not common, it may happen. The NNLS algorithm uses a heuristic to determine the next parameter to optimize. Any heuristic may cause an infinite loop under certain conditions that depend on the particular heuristic. Currently there is only one heuristic implemented, the maximum descent heuristic. Hence the problem cannot be solved by resorting to another heuristic that may succeed for your specific problem. 

If, however, you are interested in an approx. solution, you may set the max_iter argument to the NNLS constructor to a positive value. This will cause the optimization to abort after the specified number of iterations and returning a partial (possibly bad) solution.

**Comment by giordi91** [comment]
Thank you that was most helpful, although I had trouble providing all the proper arguments for the second signature, I hacked it in making _max_iters public, just as a test. I get an assertion
k<rows, although the very same system works with the lest square in eigen.

Here is my matrix:

![image](https://cloud.githubusercontent.com/assets/2525797/17985732/fb957420-6b0e-11e6-9b73-732f4f3c5d6a.png)

It is a series of R^3 points, one for each column, and I am solving with a point moving in space and trying to find the least square. The point is R^3 too. 

Do you have any idea why the assertion is triggering? I do understand those being silly question as stated above I am not confident (yet) with the details of the math itself.

Regards

M.

**Comment by hmatuschek** [comment]
It appears that you have to pass the transposed matrix. The matrix shown in the image contains more columns than rows. The NNLS (as well as a LS) problem is of the form

argmin ||y - Ab ||^2

where y is some given n vector, A is a given n x m Matrix and b (the solution) will be a m-vector. where n>=m (usually n>m).
