### ISSUE TITLE
Plans on support SparseMatrix?

### ISSUE THREAD

**Issue by pramanc** [hmatuschek/eigen3-nnls#5]
Really nice work! but I need NNLS on sparseMatrix, do you have any plan?

**Comment by hmatuschek** [comment]
Actually no. It makes no sens to throw a QR-like decomposition onto sparse matrices as the result is usually not sparse anymore. Consequently, a non-negative iterative solver would be more appropriate.

**Comment by pramanc** [comment]
Thanks for the replay!

**Comment by hmatuschek** [comment]
Not now.
